Fix fo CentOS 6 and Debian 8
Sinusbot/installer-linux pull request #7
Opened 2017-06-05 23:28 UTC by xteo007

2017-06-06 10:59 UTC, maxibanki commented on sinusbot_installer.sh
> +LATEST_VERSION=$(wget -q --no-check-certificate --timeout=60 -O - https://raw.githubusercontent.com/SinusBot/installer-linux/master/sinusbot_installer.sh | grep -Po '(?<=Instversion=")([0-9]\.[0-9]\.
Maybe the better way is to update the ca-certificates at the beginning of the script instead of adding the `--no-check-certificate` every time.

2017-06-06 11:00 UTC, maxibanki commented on sinusbot_installer.sh
> +TEMP_OS_VERSION=$( cat /etc/redhat-release | grep -oE --max-count=1 '([0-9])' | grep -oE '[0-9]' --max-count=1 )
Looks fine

2017-06-06 11:33 UTC, mxschmitt requested changes
- Revert the commit 789ffc04b5dad850d01f904441b39ed678e61995

2017-06-06 11:40 UTC, maxibanki commented on sinusbot_installer.sh
> +if [ "$TEMP_OS_VERSION" -ge 7 ]; then
Looks fine, as far as I researched is timedatectl not available in CentOS 6.

2017-06-06 11:42 UTC, maxibanki commented on sinusbot_installer.sh
> +LATEST_VERSION=$(wget -q --no-check-certificate --timeout=60 -O - https://raw.githubusercontent.com/SinusBot/installer-linux/master/sinusbot_installer.sh | grep -Po '(?<=Instversion=")([0-9]\.[0-9]\.
Already integrated with my PR. So please revert that it won't be a merge conflict.

2017-06-06 11:42 UTC, maxibanki commented on sinusbot_installer.sh
> +if [ "$TEMP_OS_VERSION" -ge 7 ]; then
Looks fine, as far as I researched is timedatectl not available in CentOS 6.

2017-06-07 13:01 UTC, DAThosting commented
@maxibanki Fixed this in https://github.com/Sinusbot/installer-linux/pull/8

2017-06-07 13:01 UTC, closed without merging